version: '3'


services:
  app:

    build:
      context: .
      target: ${NODE_ENV}
      dockerfile: Dockerfile
    
    volumes:
      - .:/app/
      - /app/node_modules

    container_name: nest-seltec
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_VERSION: ${APP_VERSION}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}